version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./public:/var/www/html
            # - ./conf.d:/etc/nginx/conf.d
      # - ./certbot/conf:/etc/nginx/ssl
      # - ./certbot/data:/var/www/certbo
    ports:
      - 80:80
      - 443:443
      
    depends_on:
      - backend
      - frontend

  redis:
    image: redis
    ports:
      - 6379:6379
  # certbot:
  #       image: certbot/certbot:latest
  #       command: certonly --webroot --webroot-path=/var/www/certbot --email test@domain.com --agree-tos --no-eff-email -d test.thiere18.studio -d www.test.thiere18.studio
  #       volumes:
  #           - ./certbot/conf:/etc/letsencrypt
  #           - ./certbot/logs:/var/log/letsencrypt
  #           - ./certbot/data:/var/www/certbot
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5431:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

  flower:  
    image: mher/flower
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:  
        - 5555:5555
    depends_on:
      - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/postgres'
    depends_on:
      - "postgres"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development


volumes:
  db-data:
